---
# Create Namespace

apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
# Create Secret (echo -n your_password | base64)

apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
type: Opaque
data:
  password: W&EHNDJGRHKWdc
---
# Create Persistent Volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pihole"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "500Mi"
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/chlabpihole01/pihole
    server: 192.168.15.21
---
# Create Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "pihole"
  name: "pihole"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "500Mi"
---

# Ingress

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: pihole
  name: pihole-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: chlabpihole.chlab.local #change the name to your fqdn
    http:
      paths:
        - path: /
          backend:
            serviceName: pihole-tcp
            servicePort: 80
  tls:                         #If you are not using certificates remove tls part
  - hosts:
    - chlabpihole.chlab.local
    secretName: secret-pihole

---
